_target_: diffusion_policy.workspace.train_robomimic_image_workspace.TrainRobomimicImageWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_score={test_mean_score:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_score
dataloader:
  batch_size: 64
  num_workers: 16
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 10
exp_name: default
horizon: 10
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: ${now:%Y.%m.%d-%H.%M.%S}_train_lstm_image_square_image_single_clip
  project: LeTO_test
  resume: true
  tags:
  - train_robomimic_image
  - square_image
  - default
multi_run:
  run_dir: data/outputs/2023.01.06/19.56.58_train_robomimic_image_square_image
  wandb_name_base: 2023.01.06-19.56.58_train_robomimic_image_square_image
n_action_steps: 1
n_latency_steps: 0
n_obs_steps: 1
name: train_robomimic_image
policy:
  _target_: diffusion_policy.policy.robomimic_image_policy.RobomimicImagePolicy
  algo_name: bc_rnn
  crop_shape:
  - 76
  - 76
  dataset_type: mh
  obs_type: image
  shape_meta:
    action:
      shape:
      - 7
    obs:
      agentview_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
  task_name: square
shape_meta:
  action:
    shape:
    - 7
  obs:
    agentview_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_eef_pos:
      shape:
      - 3
    robot0_eef_quat:
      shape:
      - 4
    robot0_eye_in_hand_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_gripper_qpos:
      shape:
      - 2
task:
  abs_action: false
  dataset:
    _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
    abs_action: false
    dataset_path: data/robomimic/datasets/square/mh/image.hdf5
    horizon: 10
    n_obs_steps: 10
    pad_after: 0
    pad_before: 0
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 7
      obs:
        agentview_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
    use_cache: true
    use_legacy_normalizer: false
    val_ratio: 0.02
  dataset_path: data/robomimic/datasets/square/mh/image.hdf5
  dataset_type: mh
  env_runner:
    _target_: LeTO.env_runner.LeTO_robomimic_image_single_clip_runner.LetoRobomimicImageSingleClipRunner
    abs_action: false
    crf: 22
    dataset_path: data/robomimic/datasets/square/mh/image.hdf5
    fps: 10
    max_steps: 600
    n_action_steps: 1
    n_envs: 28
    n_obs_steps: 1
    n_test: 25
    n_test_vis: 4
    n_train: 3
    n_train_vis: 2
    render_obs_key: agentview_image
    shape_meta:
      action:
        shape:
        - 7
      obs:
        agentview_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_eef_pos:
          shape:
          - 3
        robot0_eef_quat:
          shape:
          - 4
        robot0_eye_in_hand_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        robot0_gripper_qpos:
          shape:
          - 2
    test_start_seed: 100
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  name: square_image
  shape_meta:
    action:
      shape:
      - 7
    obs:
      agentview_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
  task_name: square
task_name: square_image
training:
  checkpoint_every: 1
  debug: false
  device: cuda:0
  max_train_steps: null
  max_val_steps: null
  num_epochs: 3000
  resume: true
  rollout_every: 10
  seed: 42
  tqdm_interval_sec: 1.0
  val_every: 1
  sample_every: 5
val_dataloader:
  batch_size: 64
  num_workers: 16
  persistent_workers: false
  pin_memory: true
  shuffle: false

